---
groups:
  - name: terraform-rds
    jobs:
    - terraform-rds

jobs:
  - name: terraform-rds
    plan:
    - get: bosh-src
    - put: brats-terraform
      params:
        env_name: my-rds
        terraform_source: bosh-src/ci/brats
        action: destroy
        vars:
          rds_mysql_username: ((brats-rds-mysql-external-db-user))
          rds_mysql_password: ((brats-rds-mysql-external-db-password))
          rds_mysql_databasename: ((brats-rds-mysql-external-db-name))
          rds_postgres_username: ((brats-rds-postgres-external-db-user))
          rds_postgres_password: ((brats-rds-postgres-external-db-password))
          rds_postgres_databasename: ((brats-rds-postgres-external-db-name))
          aws_access_key_id: ((bosh-ci-database-terraform-rds-aws-access-key-id))
          aws_secret_access_key: ((bosh-ci-database-terraform-rds-aws-secret-access-key))
          gcp_mysql_username: ((brats-gcp-mysql-external-db-user))
          gcp_mysql_password: ((brats-gcp-mysql-external-db-password))
          gcp_mysql_databasename: ((brats-gcp-mysql-external-db-name))
          gcp_postgres_username: ((brats-gcp-postgres-external-db-user))
          gcp_postgres_password: ((brats-gcp-postgres-external-db-password))
          gcp_postgres_databasename: ((brats-gcp-postgres-external-db-name))
      get_params:
        action: destroy
    - put: brats-terraform
      params:
        env_name: my-rds
        terraform_source: bosh-src/ci/brats
        vars:
          rds_mysql_username: ((brats-rds-mysql-external-db-user))
          rds_mysql_password: ((brats-rds-mysql-external-db-password))
          rds_mysql_databasename: ((brats-rds-mysql-external-db-name))
          rds_postgres_username: ((brats-rds-postgres-external-db-user))
          rds_postgres_password: ((brats-rds-postgres-external-db-password))
          rds_postgres_databasename: ((brats-rds-postgres-external-db-name))
          aws_access_key_id: ((bosh-ci-database-terraform-rds-aws-access-key-id))
          aws_secret_access_key: ((bosh-ci-database-terraform-rds-aws-secret-access-key))
          gcp_mysql_username: ((brats-gcp-mysql-external-db-user))
          gcp_mysql_password: ((brats-gcp-mysql-external-db-password))
          gcp_mysql_databasename: ((brats-gcp-mysql-external-db-name))
          gcp_postgres_username: ((brats-gcp-postgres-external-db-user))
          gcp_postgres_password: ((brats-gcp-postgres-external-db-password))
          gcp_postgres_databasename: ((brats-gcp-postgres-external-db-name))
        env:
          GOOGLE_CREDENTIALS: ((bosh-ci-database-terraform-google-credentials))
    - task: show-outputs
      config:
        platform: linux
        inputs:
          - name: brats-terraform
        run:
          path: /bin/sh
          args:
            - -c
            - |
                echo "name: $(cat brats-terraform/name)"
                echo "metadata: $(cat brats-terraform/metadata)"

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

resources:
- name: bosh-src
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh
    branch: master
- name: brats-terraform
  type: terraform
  source:
    storage:
      bucket: bosh-ci-terraform
      bucket_path: brats-ci/
      region_name: us-west-1
      access_key_id: ((bosh-ci-database-terraform-aws-access-key-id))
      secret_access_key: ((bosh-ci-database-terraform-aws-secret-access-key))
    vars:
      # RDS_MYSQL_EXTERNAL_DB_HOST: ((brats-rds-mysql-external-db-host)) # needs to come from the terraform output
      # rds_mysql_username: ((brats-rds-mysql-external-db-user))
      # rds_mysql_password: ((brats-rds-mysql-external-db-password))
      # rds_mysql_databasename: ((brats-rds-mysql-external-db-name))
      # RDS_POSTGRES_EXTERNAL_DB_HOST: ((brats-rds-postgres-external-db-host))
      # RDS_POSTGRES_EXTERNAL_DB_USER: ((brats-rds-postgres-external-db-user))
      # RDS_POSTGRES_EXTERNAL_DB_PASSWORD: ((brats-rds-postgres-external-db-password))
      # RDS_POSTGRES_EXTERNAL_DB_NAME: ((brats-rds-postgres-external-db-name))
      # GCP_MYSQL_EXTERNAL_DB_HOST: ((brats-gcp-mysql-external-db-host))
      # GCP_MYSQL_EXTERNAL_DB_USER: ((brats-gcp-mysql-external-db-user))
      # GCP_MYSQL_EXTERNAL_DB_PASSWORD: ((brats-gcp-mysql-external-db-password))
      # GCP_MYSQL_EXTERNAL_DB_NAME: ((brats-gcp-mysql-external-db-name))
      # GCP_MYSQL_EXTERNAL_DB_CLIENT_CERTIFICATE: ((brats-gcp-mysql-external-db-client-certificate))
      # GCP_MYSQL_EXTERNAL_DB_CLIENT_PRIVATE_KEY: ((brats-gcp-mysql-external-db-client-private-key))
      # GCP_POSTGRES_EXTERNAL_DB_HOST: ((brats-gcp-postgres-external-db-host))
      # GCP_POSTGRES_EXTERNAL_DB_USER: ((brats-gcp-postgres-external-db-user))
      # GCP_POSTGRES_EXTERNAL_DB_PASSWORD: ((brats-gcp-postgres-external-db-password))
      # GCP_POSTGRES_EXTERNAL_DB_NAME: ((brats-gcp-postgres-external-db-name))
      # GCP_POSTGRES_EXTERNAL_DB_CLIENT_CERTIFICATE: ((brats-gcp-postgres-external-db-client-certificate))
      # GCP_POSTGRES_EXTERNAL_DB_CLIENT_PRIVATE_KEY: ((brats-gcp-postgres-external-db-client-private-key))

